### ISSUE TITLE
Suggestion: Organisation des Commandes

### ISSUE THREAD

**Issue by D34DPlayer** [AH-REM/discord-noob#1]
De la façon dont le framework est organisé actuellement, les Commandes ont comme pilier central le message qu'elles retournent. Une meilleure abstraction serait de séparer cette création de message et plutôt centrer les Commandes sur une fonction (ou script, appelle le comme tu veux) quelconque qui sera exécutée lors de l'appel, dont une pourrait être la création de message déjà présente.

De cette façon une Commande ne serait plus définie par le message qu'elle retourne mais plutôt par ce qu'elle fait lorsqu'elle est appelée, cela permettrait d'avoir des réponses bien plus dynamiques et me permettrait d’implémenter mes vérifications, groupes et commande d'aide.

**Comment by D34DPlayer** [comment]
Un exemple se trouve dans mon fork, dans le commit correspondant, j'ai ajouté le path des scripts comme une option du client mais un Loader spécifique pourrait être envisagé.

**Comment by AH-REM** [comment]
Je viens de commencer à commit mes modifications à propos du systèmes d'action/script, tu me diras si c'est bon pour toi. Le constructeur de la classe Command est un peu moche actuellement, je verrais si je peux pas modifier, pour faire quelque chose de plus correct.
